# Generated by Django 2.0.7 on 2018-07-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automationlookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlookup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lookup', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
